micronaut:
  application:
    name: nauthorus
  caches:
    rates:
      charset: 'UTF-8'
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
netty:
  default:
    allocator:
      max-order: 3
jpa.default.properties.hibernate.hbm2ddl.auto: update
exchange-rate-api:
  baseUrl: http://api.exchangeratesapi.io/v1
  api-key: ba99491b4d18b57a0ebd5779f62d745c
  format: 1